Projekt_Geppert_Lener/Projekt_Geppert_Lener/Controllers/marketController.cs
using MySql.Data.MySqlClient;
using Projekt_Geppert_Lener.Models;
using Projekt_Geppert_Lener.Models.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace Projekt_Geppert_Lener.Controllers
{
    public class MarketController : Controller
    {
        RepArticle repArticle = new RepArticle();
        // GET: market
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MarketOverview()
        {
            List<Article> a;
            try
            {
                repArticle.Open();
                a = repArticle.GetAllArticles();
            }
            catch (MySqlException)
            {
                return View("Message", new Message("Datenbankfehler", "Es gibt zur Zeit ein Problem mit der Datenbank"));
            }
            catch (Exception)
            {
                return View("Message", new Message("Allgemeiner Fehler", "Ein allgemeiner Fehler ist aufgetreten"));
            }
            finally
            {
                repArticle.Close();
            }
            if (a != null)
            {
                a = GetUnofficial(a);
            }
            else
            {
                a = null;
            }
            return View(a);
        }

        public ActionResult MarketDetailed(int id)
        {
            Article a;
            try
            {
                repArticle.Open();
                a = repArticle.GetOneArticle(id);
            }
            catch (MySqlException)
            {
                return View("Message", new Message("Datenbankfehler", "Es gibt zur Zeit ein Problem mit der Datenbank"));
            }
            catch (Exception)
            {
                return View("Message", new Message("Allgemeiner Fehler", "Ein allgemeiner Fehler ist aufgetreten"));
            }
            finally
            {
                repArticle.Close();
            }
            return View(a);
        }

        [HttpGet]
        public ActionResult AddArticleToMarket()
        {
            User u = (User)Session["loggedInUser"];
            if (u != null)
            {
                Article ar = new Article();
                ar.IsOfficial = false;
                return View(ar);
            }
            else
            {
                return View("Message", new Message("Login", "Sie sind nicht eingelogged."));
            }
        }

        [HttpPost]
        public ActionResult AddArticleToMarket(Article articleDataFromForm)
        {
            User u = (User)Session["loggedInUser"];
            if (u != null)
            {
                articleDataFromForm.Seller = u.Username;
                articleDataFromForm.IsOfficial = false;
                if (articleDataFromForm != null)
                {
                    try
                    {
                        repArticle.Open();
                        if (ModelState.IsValid)
                        {
                            //Pfad für gespeicherte Datei am Server generieren
                            string path = Path.Combine(Server.MapPath("~/Media/shop/"), Path.GetFileName(articleDataFromForm.Img.FileName));

                            //Bild auf diesem Pfad speichern
                            articleDataFromForm.Img.SaveAs(path);
                            //Pfad in Objekt setzen, damit dieser in der Datenbank verfügbar ist
                            articleDataFromForm.ImagePath = "/Media/shop/" + Path.GetFileName(articleDataFromForm.Img.FileName);
                            repArticle.AddArticle(articleDataFromForm);
                            ViewBag.Message = "File uploaded successfully";
                            repArticle.AddArticle(articleDataFromForm);
                        }
                    }
                    catch (MySqlException)
                    {
                        return View("Message", new Message("Datenbankfehler", "Es gibt zur Zeit ein Problem mit der Datenbank"));
                    }
                    catch (Exception)
                    {
                        return View("Message", new Message("Allgemiener Fehler", "Ein allgemeiner Fehler ist aufgetreten"));
                    }
                    finally
                    {
                        repArticle.Close();
                    }
                    if (ModelState.IsValid)
                    {
                        return View("Message", new Message("Artikel hinzufügen", "Erfolgreich hinzugefügt"));
                    }
                    else
                    {
                        return View(articleDataFromForm);
                    }
                }
                else
                {
                    return RedirectToAction("AddArticle");
                }
            }
            else
            {
                return View("Message", new Message("Login", "Sie sind nicht eingelogged."));
            }
        }

        public List<Article> GetUnofficial(List<Article> allArticles)
        {
            List<Article> officialArticles = new List<Article>();
            foreach (Article a in allArticles)
            {
                if (a.IsOfficial == false)
                {
                    officialArticles.Add(a);
                }
            }
            if (officialArticles.Count > 0)
            {
                return officialArticles;
            }
            else
            {
                return null;
            }
        }

        public ActionResult sendMessage(string seller)
        {
            User u = (User)Session["loggedInUser"];
            if (u != null)
            {
                if(seller != null)
                {
                    Session["Seller"] = seller;
                    return RedirectToAction("newMessage","Chat");
                }
                else
                {
                    return View("Message", new Message("Error", "Verkäufer nicht gefunden."));
                }
            }
            else
            {
                return View("Message", new Message("Login", "Sie sind nicht eingelogged."));
            }
        }
    }
}

Projekt_Geppert_Lener/Projekt_Geppert_Lener/Views/Market/AddArticleToMarket.cshtml
@model Projekt_Geppert_Lener.Models.Article

@{
    ViewBag.Title = "AddArticleToMarket";
}


<div style="margin-left:35em">
    <h2 class="display-4">Hier können Sie Artikel hinzufügen</h2>
    @using (Html.BeginForm("AddArticleToMarket", "market", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
    <div class="col-sm-4">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="fnLabel">Name des Produkts</span>
            </div>
            @Html.TextBoxFor(p => p.Name)
            @Html.ValidationMessageFor(p => p.Name)
        </div>


        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="lnLabel">Preis</span>
            </div>
            @Html.TextBoxFor(p => p.Price)
            @Html.ValidationMessageFor(p => p.Price)
        </div>


        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="inputGroupSelect01">ArtikelTyp</label>
            </div>
            @Html.EnumDropDownListFor(p => p.ArticleType)
            @Html.ValidationMessageFor(p => p.ArticleType)
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="unameLabel">Auf Lager</span>
            </div>
            @Html.TextBoxFor(p => p.Amount)
            @Html.ValidationMessageFor(p => p.Amount)
        </div>

        <label for="file">Upload Image:</label>
        @*<input type="file" name="Img" id="Img" required />*@
        @Html.TextBoxFor(p => p.Img, new { type = "file" })

        <button class="btn btn-primary" type="submit">Hinzufügen!</button>
        <button class="btn btn-primary" type="reset">Abbrechen</button>


    </div>
    }
</div>

Projekt_Geppert_Lener/Projekt_Geppert_Lener/Views/Market/Index.cshtml
<p>Indexseite</p>

Projekt_Geppert_Lener/Projekt_Geppert_Lener/Views/Market/MarketDetailed.cshtml
@model Projekt_Geppert_Lener.Models.Article
@using Projekt_Geppert_Lener.Models

@{
    ViewBag.Title = "MarketDetailed";
}

<h2 class="display-4 center-block text-center">Schau es dir genauer an!</h2>

@if ((Model != null) && (Session["loggedInUser"] != null))
{
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="@Model.ImagePath" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Verhandlungsbasis:@Model.Price</li>
            <li class="list-group-item">Verkäufer:@Model.Seller</li>
            <li class="list-group-item">Typ:@Model.ArticleType</li>
            <li class="list-group-item">Auf Lager:@Model.Amount</li>
        </ul>
        <div class="card-body">
            <a href="#" class="card-link">@Html.ActionLink("zurück zu alle Artikel", "MarketOverview", "Market")</a>
            <a href="/market/sendMessage/?seller=@Model.Seller" class="card-link">Kontakt zum Käufer herstellen</a>
        </div>
    </div>
}
else if (Session["loggedInUser"] != null)
{
    <p>kein Artikel vorhanden</p>
    <p>@Html.ActionLink("zurück zu alle Artikel", "ArticleOverview", "shop")</p>
}
else
{
    <p>@Html.ActionLink("Sie müssen sich zuerst anmelden", "login", "user")</p>
}

Projekt_Geppert_Lener/Projekt_Geppert_Lener/Views/Market/MarketOverview.cshtml
@model List<Projekt_Geppert_Lener.Models.Article>
@using Projekt_Geppert_Lener.Models

@{
    ViewBag.Title = "MarketOverview";
}

<h2 class="display-4 center-block text-center">Kaufe von anderen Mitgliedern!</h2>

@if (Model != null)
{

    <body>
        @foreach (Article a in Model)
        {
            
                <div class="card" style="width: 18rem;">
                    <img src="@a.ImagePath" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@a.Name</h5>
                        <p class="card-text">@a.Price € (Verhandlungsbasis)</p>
                        <a class="btn btn-primary" href="MarketDetailed/@a.ID" )>zum Produkt</a>
                    </div>
                </div>
            

        }
    </body>
}
else
{
    <p>kein Artikel vorhanden</p>
}